### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by danomatika**
See commits below.

Also, what is touch-orig.pd? Is that just something left over from a PR etc? Can it be removed?

### CODE REVIEW

**Comment by danomatika** [comment]
Latest commit resizes internal UIs of the follow abstractions to match their canvas sizes. This makes them look and act more like their mobile implementations:

* display.pd
* taplist.pd
* numberbox.pd

Here's a screenshot of all 3 at the same size, 200x100:

screen shot 2016-01-11 at 9 43 04 pm

**Comment by danomatika** [comment]
ping @chr15m

**Comment by chr15m** [comment]
Will merge, sorry for the delay! 

On 18 January 2016 6:32:24 am AWST, Dan Wilcox <notifications@github.com> wrote:
>ping @chr15m 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/chr15m/PdDroidParty/pull/31#issuecomment-172391336

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chr15m** [comment]
Nice.

**Pull request merged**
